PresentationLayer/Controllers/JobsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Mvc;
using BusinessLayer.DTOs;
using BusinessLayer.DTOs.Filters;
using BusinessLayer.Facades;
using BusinessLayer.Facades.Employers;
using BusinessLayer.Facades.JobOffer;
using BusinessLayer.Facades.RegisteredUsers;
using PresentationLayer.Helpers;
using PresentationLayer.Models.JobOffer;
using HttpPost = System.Web.Mvc.HttpPostAttribute;

namespace PresentationLayer.Controllers
{
    public class JobsController : Controller
    {
	    public JobOfferFacade JobOfferFacade { get; set; }
		public EmployerFacade EmployerFacade { get; set; }
		public RegisteredUserFacade RegisteredUserFacade { get; set; }
		public OfficeSelectListHelper OfficeSelectListHelper { get; set; }
        public SkillFacade SkillFacade { get; set; }

		// GET: Job
		public async Task<ActionResult> Index(int page = 1)
        {
            JobOfferFilterDto filter = new JobOfferFilterDto
            {
                PageSize = JobPortalSettings.DefaultPageSize,
                RequestedPageNumber = page
            };

	        var jobs = await this.JobOfferFacade.Get(filter);
	        return View("Index", jobs);
		}

        // GET: Jobs/Filter/{skill-name}
        public async Task<ActionResult> Filter(string skill)
        {
            var jobs = await JobOfferFacade.GetBySkill(skill);
            return View("Index", jobs);
        }

        // POST: Job/Filter/Dto
        //public async Task<ActionResult> Filter([FromBody]JobOfferFilterDto filter)
		//{
		//	var jobs = await this.JobOfferFacade.Get(filter);
		//	return View("Index", jobs);
		//}

	    // GET: Job/Details/5
	    public async Task<ActionResult> Details(int id)
	    {
		    JobOfferDto job = await this.JobOfferFacade.Get(id);
		    if (job != null)
		    {
			    return View(job);
		    }
		    throw new HttpResponseException(HttpStatusCode.NotFound);
		}

        // GET: Jobs/Create
        [System.Web.Mvc.Authorize(Roles = "Employer")]
        public async Task<ActionResult> Create()
        {
            JobOfferCreateViewModel model = new JobOfferCreateViewModel
            {
                Offices = await OfficeSelectListHelper.Get(),
                NumberOfQuestions = 1,
                NumberOfSkills = 1
            };

            return View(model);
        }

        // POST: Jobs/Create
        [HttpPost]
        [System.Web.Mvc.Authorize(Roles = "Employer")]
        public async Task<ActionResult> Create(JobOfferCreateViewModel model)
        {
            if (!CorrectNumberOfQuestions(model) || NumberOfSkillsChanged(model) || !ModelState.IsValid)
            {
                if (NumberOfSkillsChanged(model))
                {
                    ModelState.Remove("NumberOfSkills");
                    ChangeNumberOfSkills(model);
                }

                model.Offices = await OfficeSelectListHelper.Get();
                return View(model);
            }

	        try
	        {
		        var jobDto = model.JobOfferCreateDto;
		        var currentEmployer = await EmployerFacade.GetByUsername(User.Identity.Name);
		        jobDto.EmployerId = currentEmployer.Id;

		        JobOfferFacade.Create(jobDto);

		        return RedirectToAction("Index", "EmployerAdmin");
			}
	        catch
			{
				model.Offices = await OfficeSelectListHelper.Get();
				return View(model);
			}
        }

        // Used by skill autocomplete
        public async Task<ActionResult> GetSkills(string term)
        {
            return Json((await SkillFacade.GetAllSkills()).Items
                        .Where(c => c.Name.ToUpper().StartsWith(term.ToUpper()))
                        .Select(a => new { label = a.Name }), JsonRequestBehavior.AllowGet);
        }

        #region Helpers (VERY UGLY, should use javascript instead)

        private bool CorrectNumberOfQuestions(JobOfferCreateViewModel model)
        {
            if (Request.Form["ChangeQuestions"] != null)
            {
                if (model.JobOfferCreateDto.Questions == null)
                {
                    model.JobOfferCreateDto.Questions = new List<QuestionDto>();
                }
                while (model.JobOfferCreateDto.Questions.Count < model.NumberOfQuestions)
                {
                    model.JobOfferCreateDto.Questions.Add(new QuestionDto());
                }
                return false;
            }
            return true;
        }

        private bool NumberOfSkillsChanged(JobOfferCreateViewModel model)
        {
            return NumberOfSkillsIncreased(model) || NumberOfSkillsDecreased(model);
        }

        private bool NumberOfSkillsIncreased(JobOfferCreateViewModel model)
        {
            if (Request.Form["AddSkill"] != null)
            {
                return true;
            }
            return false;
        }

        private bool NumberOfSkillsDecreased(JobOfferCreateViewModel model)
        {
            if (Request.Form["RemoveSkill"] != null)
            {
                return true;
            }
            return false;
        }

        private void ChangeNumberOfSkills(JobOfferCreateViewModel model)
        {
            if (model.JobOfferCreateDto.Skills == null)
            {
                model.JobOfferCreateDto.Skills = new List<SkillDto>();
            }

            if (NumberOfSkillsIncreased(model))
            {
                model.JobOfferCreateDto.Skills.Add(new SkillDto());
                model.NumberOfSkills++;
            }

            if (NumberOfSkillsDecreased(model) && model.NumberOfSkills > 1)
            {
                model.JobOfferCreateDto.Skills.RemoveAt(model.NumberOfSkills - 1);
                model.NumberOfSkills--;
            }
        }

        #endregion
    }
}

PresentationLayer/Controllers/RegisteredUserAdminController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using BusinessLayer.DTOs.Filters;
using BusinessLayer.Facades.JobApplication;
using BusinessLayer.Facades.RegisteredUsers;

namespace PresentationLayer.Controllers
{
	/// <summary>
	/// Registruje userov, useri si mozu menit skilly, educations, atd
	/// </summary>
	[Authorize(Roles = "User" /*Role.User.GetString()*/)]
	public class RegisteredUserAdminController : Controller
	{
		public RegisteredUserFacade RegisteredUserFacade { get; set; }
		public JobApplicationFacade JobApplicationFacade { get; set; }

		// GET: RegisteredUser
		public async Task<ActionResult> Index(int page = 1)
		{
			var user = await RegisteredUserFacade.GetByUsername(User.Identity.Name);

			JobApplicationFilterDto filter = new JobApplicationFilterDto
			{
				PageSize = JobPortalSettings.DefaultPageSize,
				RequestedPageNumber = page,
				JobCandidateId = user.Id
			};

			var applications = await this.JobApplicationFacade.Get(filter);
			return this.View(applications);
		}
    }
}

PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - JobPortal 3000</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("JobPortal 3000", "Index", "Jobs", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Jobs", "Index", "Jobs")</li>
                    @*<li>@Html.ActionLink("Users", "Index", "Users")</li>*@
                    <li>@Html.ActionLink("Employers", "Index", "Employer")</li>
                    
                @if (User.IsInRole("User"))
                {
                    <li>@Html.ActionLink("User panel", "Index", "RegisteredUserAdmin")</li>
                }
                else if (User.IsInRole("Employer"))
                {
                    <li>@Html.ActionLink("Employer panel", "Index", "EmployerAdmin")</li>
                }
                else
                {
                    <li>@Html.ActionLink("My panel", "Login", "Account")</li>
                }

                </ul>
                <ul class="nav navbar-nav  navbar-right">
                    @if (Request.IsAuthenticated)
                    {
                    <li class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user grey"></span> @User.Identity.Name.Split('@')[0] <b class="caret grey"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Account management</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                        </ul>
                    </li>}
                    else
                    {
                    <li class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user grey"></span><b class="caret grey"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Get started</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Register user", "RegisterUser", "Account")</li>
                            <li>@Html.ActionLink("Register employer", "RegisterEmployer", "Account")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Log in", "Login", "Account")</li>
                        </ul>
                    </li>}
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("css", required: false)
    @RenderSection("scripts", required: false)
</body>
</html>