PresentationLayer/Models/JobApplication/JobApplicationCreateViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using BusinessLayer.DTOs;

namespace PresentationLayer.Models.JobApplication
{
	public class JobApplicationCreateViewModel
	{
		public IEnumerable<SelectListItem> Educations { get; set; }

		public JobApplicationCreateDto JobApplicationCreateDto { get; set; }
	}
}

PresentationLayer/Controllers/JobApplicationController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using BusinessLayer.DTOs;
using BusinessLayer.Facades.JobApplication;
using BusinessLayer.Facades.JobOffer;
using BusinessLayer.Facades.RegisteredUsers;
using Castle.Core.Internal;
using PresentationLayer.Helpers;
using PresentationLayer.Models.JobApplication;

namespace PresentationLayer.Controllers
{
    /// <summary>
    /// Vytvara a vybavuje job applications
    /// </summary>
    public class JobApplicationController : Controller
    {
	    public JobApplicationFacade JobApplicationFacade { get; set; }
		public RegisteredUserFacade RegisteredUserFacade { get; set; }
		public JobOfferFacade JobOfferFacade { get; set; }
		public EducationSelectListHelper EducationSelectListHelper { get; set; }

		// GET: JobApplication/Details/5
		public async Task<ActionResult> Details(int id)
		{
			JobApplicationDto application = await this.JobApplicationFacade.Get(id);
			return View(application);
        }

        // GET: JobApplication/Create/5
        public async Task<ActionResult> Create(int id)
        {
            JobOfferDto jobOffer = await JobOfferFacade.Get(id, false);
            var candidate = User.Identity.Name.IsNullOrEmpty()
                ? new JobCandidateDto()
                : await RegisteredUserFacade.GetByUsername(User.Identity.Name);

            JobApplicationCreateDto applicationCreateDto = new JobApplicationCreateDto
            {
                JobOfferId = jobOffer.Id,
                JobOfferName = jobOffer.Name,
                JobOffer = jobOffer,
                Answers = CreateEmptyAnswers(jobOffer),
                CandidateDto = candidate
            };

            JobApplicationCreateViewModel model = new JobApplicationCreateViewModel
            {
                JobApplicationCreateDto = applicationCreateDto,
                Educations = EducationSelectListHelper.Get()
            };

            return View(model);
        }

        // POST: JobApplication/Create
        [HttpPost]
        public async Task<ActionResult> Create(JobApplicationCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var jobOffer = await JobOfferFacade.Get(model.JobApplicationCreateDto.JobOfferId);
                model.JobApplicationCreateDto.JobOfferName = jobOffer.Name;
                model.JobApplicationCreateDto.JobOffer = jobOffer;

                var candidate = User.Identity.Name.IsNullOrEmpty()
                    ? new JobCandidateDto()
                    : await RegisteredUserFacade.GetByUsername(User.Identity.Name);

                model.JobApplicationCreateDto.CandidateDto = candidate;

                model.Educations = EducationSelectListHelper.Get();
                return View(model);
            }

            try
            {
                this.JobApplicationFacade.Create(model.JobApplicationCreateDto);
                return RedirectToAction("Details", "Jobs", new { id = model.JobApplicationCreateDto.JobOfferId });
            }
            catch
            {
                return View();
            }
        }

        // HELPERS //

        private static List<AnswerDto> CreateEmptyAnswers(JobOfferDto jobOffer)
		{
			int questionsCount = jobOffer.Questions.Count;
			var list = new List<AnswerDto>(questionsCount);
		    for (int i = 0; i < questionsCount; i++)
		    {
			    QuestionDto question = jobOffer.Questions[i];
			    list.Add(new AnswerDto
			    {
				    QuestionId = question.Id,
				    Question = question
			    });
		    }
		    return list;
	    }
	}
}

PresentationLayer/Controllers/RegisteredUserAdminController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using BusinessLayer.DTOs.Filters;
using BusinessLayer.Facades.JobApplication;
using BusinessLayer.Facades.RegisteredUsers;

namespace PresentationLayer.Controllers
{
	/// <summary>
	/// Registruje userov, useri si mozu menit skilly, educations, atd
	/// </summary>
	[Authorize(Roles = "User" /*Role.User.GetString()*/)]
	public class RegisteredUserAdminController : Controller
	{
		public RegisteredUserFacade RegisteredUserFacade { get; set; }
		public JobApplicationFacade JobApplicationFacade { get; set; }

		// GET: RegisteredUser
		public async Task<ActionResult> Index(int page = 1)
		{
			var user = await RegisteredUserFacade.GetByUsername(User.Identity.Name);

			JobApplicationFilterDto filter = new JobApplicationFilterDto
			{
				PageSize = JobPortalSettings.DefaultPageSize,
				RequestedPageNumber = page,
				JobCandidateId = user.Id
			};

			var applications = await this.JobApplicationFacade.Get(filter);
			return this.View(applications);
		}
    }
}

PresentationLayer/Views/RegisteredUserAdmin/Index.cshtml
@model IEnumerable<BusinessLayer.DTOs.JobApplicationDto>

@{
    ViewBag.Title = "Index";
}

<h2>My job applications</h2>

<table class="table">
    <tr>
        <th>
           Job name
        </th>
        <th>
           Job description
        </th>
        <th>
            Employer
        </th>
        <th>
            Status
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.JobOffer.Name, "Details", "JobApplication", new { id=item.Id }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobOffer.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobOffer.Employer.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
    </tr>
}

</table>

PresentationLayer/Views/RegisteredUserAdmin/JobApplication.cshtml
@model BusinessLayer.DTOs.JobApplicationDto

@{
    ViewBag.Title = "JobApplication";
}

<h2>Job Application</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Job
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JobOffer.Name)
        </dd>

        <dt>
            Description
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JobOffer.Description)
        </dd>

        <dt>
            Employer
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JobOffer.Employer.Name)
        </dd>

        <dt>
            My Education
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JobCandidate.Education)
        </dd>
    </dl>
    
    
    <table class="table">
        <tr>
            <th>
                Question
            </th>
            <th>
                Answer
            </th>
            <th></th>
        </tr>
        @for(int i = 0; i < Model.Answers.Count; i++)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.Answers[i].Question.Text)
                </td>
                <td>
                    <div class="col-md-10">
                        @Html.HiddenFor(model => model.Answers[i].QuestionId)
                        @Html.HiddenFor(model => model.Answers[i].JobApplicationId)
                        @Html.EditorFor(model => model.Answers[i].Text, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => Model.Answers[i].Text, "", new { @class = "text-danger" })
                    </div>
                </td>
            </tr>
        }
    </table>

</div>
<p>@Html.ActionLink("Back to List", "Index")
</p>